/**
 * BLD-1145: covers AC6, AC7, AC17, AC19, AC20 from PLAN-BLD-1088.md
 *
 * AC6:  GTG set → PR dashboard: checkSetPR returns true for GTG set weight
 *        exceeding prior history (kind='day_session' rows have completed_at
 *        set so they appear in historical max, and a GTG set's weight is
 *        evaluated correctly).
 * AC7:  Mixed weekly volume: GTG + workout sets both contribute to volume,
 *        but "workouts this week" count excludes kind='day_session' rows.
 * AC17: Midnight-boundary test: todayDateKey returns yesterday's key at
 *        23:59:59 and today's key at 00:00:01, producing distinct day_session
 *        rows.
 * AC19: CSV round-trip: csv-import treats missing 'kind' column as 'workout'
 *        (back-compat), and day_session rows survive export → re-import.
 * AC20: Variant PR: a GTG set's weight that exceeds prior history for
 *        (exercise=pull-up) → checkSetPR returns true.
 */

// ─── Mock lib/db/helpers before any production imports ──────────────────────
jest.mock("../../../lib/db/helpers", () => ({
  query: jest.fn(),
  queryOne: jest.fn(),
  getDrizzle: jest.fn(),
  getDatabase: jest.fn(),
}));

import { DatabaseSync } from "node:sqlite";
import { drizzle as proxyDrizzle } from "drizzle-orm/sqlite-proxy";
import * as schema from "../../../lib/db/schema";
import { todayDateKey, localMidnightMs } from "../../../lib/db/day-session";
import { checkSetPR } from "../../../lib/db/session-stats";

const helpers = require("../../../lib/db/helpers") as {
  query: jest.Mock;
  getDrizzle: jest.Mock;
};

/**
 * Wire a node:sqlite in-memory DB to getDrizzle() via drizzle sqlite-proxy.
 * Applies alias fix for DISTINCT date(...) generated by Drizzle.
 */
function useDrizzleDb(db: InstanceType<typeof DatabaseSync>) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const proxyDb = proxyDrizzle(async (sql: string, params: any[], method: string) => {
    // Fix missing alias on DISTINCT date(...) expressions
    const fixedSql = sql.replace(
      /(select\s+DISTINCT\s+date\([^)]+\))(\s+from)/i,
      '$1 AS "d"$2'
    );
    const stmt = db.prepare(fixedSql);
    if (method === "run") {
      stmt.run(...params);
      return { rows: [] };
    }
    if (method === "get") {
      const row = stmt.get(...params) as Record<string, unknown> | undefined;
      return { rows: row ? [Object.values(row)] : [] };
    }
    const rows = stmt.all(...params) as Record<string, unknown>[];
    return { rows: rows.map((r) => Object.values(r)) };
  }, { schema });
  helpers.getDrizzle.mockResolvedValue(proxyDb);
}

/** Create an in-memory SQLite DB with the minimal schema for GTG tests. */
function createTestDb(): InstanceType<typeof DatabaseSync> {
  const db = new DatabaseSync(":memory:");
  db.exec(`
    CREATE TABLE exercises (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      equipment TEXT DEFAULT NULL,
      deleted_at INTEGER DEFAULT NULL
    );
    CREATE TABLE workout_sessions (
      id TEXT PRIMARY KEY,
      kind TEXT DEFAULT 'workout' NOT NULL,
      name TEXT NOT NULL DEFAULT '',
      template_id TEXT DEFAULT NULL,
      started_at INTEGER NOT NULL,
      completed_at INTEGER DEFAULT NULL,
      duration_seconds INTEGER DEFAULT NULL,
      notes TEXT DEFAULT '',
      clock_started_at INTEGER DEFAULT NULL,
      rating INTEGER DEFAULT NULL,
      edited_at INTEGER DEFAULT NULL,
      import_batch_id TEXT DEFAULT NULL,
      gym_id TEXT DEFAULT NULL,
      gym_name_at_log TEXT DEFAULT NULL,
      program_day_id TEXT DEFAULT NULL,
      day_session_exercise_id TEXT DEFAULT NULL,
      day_session_date TEXT DEFAULT NULL
    );
    CREATE TABLE workout_sets (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      exercise_id TEXT NOT NULL,
      set_number INTEGER NOT NULL,
      weight REAL DEFAULT NULL,
      reps INTEGER DEFAULT NULL,
      completed INTEGER DEFAULT 0,
      completed_at INTEGER DEFAULT NULL,
      set_type TEXT DEFAULT 'normal',
      rpe REAL DEFAULT NULL,
      notes TEXT DEFAULT NULL,
      duration_seconds INTEGER DEFAULT NULL,
      pulley_pin INTEGER DEFAULT NULL,
      bodyweight_modifier_kg REAL DEFAULT NULL,
      tempo TEXT DEFAULT NULL,
      link_id TEXT DEFAULT NULL,
      stack_id TEXT DEFAULT NULL,
      stack_marker INTEGER DEFAULT NULL,
      stack_true_weight_at_log REAL DEFAULT NULL,
      stack_unit_at_log TEXT DEFAULT NULL,
      stack_marker_at_log INTEGER DEFAULT NULL
    );
    CREATE TABLE program_schedule (
      id TEXT PRIMARY KEY,
      program_id TEXT NOT NULL,
      day_of_week INTEGER NOT NULL
    );
    CREATE TABLE programs (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      is_active INTEGER DEFAULT 0,
      deleted_at INTEGER DEFAULT NULL
    );
  `);
  return db;
}

const NOW_MS = new Date("2026-05-10T12:00:00.000Z").getTime(); // midday Saturday
const WEEK_START_MS = (() => {
  // Monday of the current week
  const d = new Date(NOW_MS);
  const dow = d.getUTCDay(); // 0=Sun, 1=Mon...
  const diff = (dow === 0 ? -6 : 1 - dow);
  d.setUTCDate(d.getUTCDate() + diff);
  d.setUTCHours(0, 0, 0, 0);
  return d.getTime();
})();

// ── AC17: Midnight boundary test ──────────────────────────────────────────

describe("BLD-1088 AC17 — midnight boundary: todayDateKey uses device-local date", () => {
  it("23:59:59 → uses the day's date key (same as 23:59:58)", () => {
    const d = new Date("2026-05-10T23:59:59.000");
    const key = todayDateKey(d);
    expect(key).toBe("2026-05-10");
  });

  it("00:00:01 → uses the next day's date key", () => {
    const d = new Date("2026-05-11T00:00:01.000");
    const key = todayDateKey(d);
    expect(key).toBe("2026-05-11");
  });

  it("midnight exactly (00:00:00) → belongs to the new day", () => {
    const d = new Date("2026-05-11T00:00:00.000");
    const key = todayDateKey(d);
    expect(key).toBe("2026-05-11");
  });

  it("two sets at 23:59:59 and 00:00:01 yield two distinct date keys", () => {
    const beforeMidnight = new Date("2026-05-10T23:59:59.000");
    const afterMidnight = new Date("2026-05-11T00:00:01.000");
    const keyBefore = todayDateKey(beforeMidnight);
    const keyAfter = todayDateKey(afterMidnight);
    expect(keyBefore).not.toBe(keyAfter);
    expect(keyBefore).toBe("2026-05-10");
    expect(keyAfter).toBe("2026-05-11");
  });

  it("localMidnightMs at 23:59:59 returns midnight of that same day (not next day)", () => {
    const d = new Date("2026-05-10T23:59:59.000");
    const midnight = localMidnightMs(d);
    const midnightDate = new Date(midnight);
    expect(midnightDate.getHours()).toBe(0);
    expect(midnightDate.getMinutes()).toBe(0);
    expect(midnightDate.getSeconds()).toBe(0);
    expect(midnightDate.getDate()).toBe(d.getDate());
  });
});

// ── AC7: Mixed weekly volume includes GTG; workouts count excludes GTG ────

describe("BLD-1088 AC7 — mixed weekly volume: GTG + workout volume counted, workout-only session count", () => {
  it("session count (workouts this week) excludes day_session rows → count = 1", () => {
    const db = new DatabaseSync(":memory:");
    db.exec(`
      CREATE TABLE workout_sessions (
        id TEXT PRIMARY KEY,
        kind TEXT DEFAULT 'workout',
        name TEXT DEFAULT '',
        started_at INTEGER NOT NULL,
        completed_at INTEGER DEFAULT NULL,
        day_session_exercise_id TEXT DEFAULT NULL,
        day_session_date TEXT DEFAULT NULL
      );
    `);

    // Regular workout (kind='workout', completed)
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at) VALUES (?, 'workout', 'Workout', ?, ?)`).run(
      "sess-workout", WEEK_START_MS + 1000, WEEK_START_MS + 3600000
    );
    // GTG day session (kind='day_session')
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date) VALUES (?, 'day_session', 'GTG', ?, ?, 'ex-pull-up', '2026-05-05')`).run(
      "sess-day", WEEK_START_MS + 2000, WEEK_START_MS + 2000
    );

    // Weekly count query — kind='workout' filter (mirrors getWeeklyWorkouts production logic)
    const row = db.prepare(`
      SELECT COUNT(*) AS cnt
      FROM workout_sessions
      WHERE kind = 'workout'
        AND completed_at IS NOT NULL
        AND started_at >= ?
        AND started_at < ?
    `).get(WEEK_START_MS, WEEK_START_MS + 7 * 24 * 60 * 60 * 1000) as { cnt: number };

    // Only the kind='workout' session counts
    expect(row.cnt).toBe(1);
  });

  it("weekly volume includes both workout AND day_session sets → volume = 650 (50×10 + 30×5)", () => {
    const db = new DatabaseSync(":memory:");
    db.exec(`
      CREATE TABLE workout_sessions (
        id TEXT PRIMARY KEY,
        kind TEXT DEFAULT 'workout',
        name TEXT DEFAULT '',
        started_at INTEGER NOT NULL,
        completed_at INTEGER DEFAULT NULL
      );
      CREATE TABLE workout_sets (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        weight REAL DEFAULT NULL,
        reps INTEGER DEFAULT NULL,
        completed INTEGER DEFAULT 0,
        set_type TEXT DEFAULT 'normal'
      );
    `);

    // Regular workout session + set: 50kg × 10 = 500 volume
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at) VALUES (?, 'workout', 'W', ?, ?)`).run(
      "sess-w", WEEK_START_MS + 1000, WEEK_START_MS + 3600000
    );
    db.prepare(`INSERT INTO workout_sets (id, session_id, weight, reps, completed, set_type) VALUES (?, ?, ?, ?, ?, ?)`).run(
      "set-w", "sess-w", 50, 10, 1, "normal"
    );

    // GTG day session + set: 30kg × 5 = 150 volume
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at) VALUES (?, 'day_session', 'G', ?, ?)`).run(
      "sess-d", WEEK_START_MS + 2000, WEEK_START_MS + 2000
    );
    db.prepare(`INSERT INTO workout_sets (id, session_id, weight, reps, completed, set_type) VALUES (?, ?, ?, ?, ?, ?)`).run(
      "set-d", "sess-d", 30, 5, 1, "normal"
    );

    // Volume query — NO kind filter (mirrors getWeeklyWorkouts production volume logic)
    const row = db.prepare(`
      SELECT COALESCE(SUM(ws.weight * ws.reps), 0) AS vol
      FROM workout_sets ws
      INNER JOIN workout_sessions wss ON ws.session_id = wss.id
      WHERE ws.completed = 1
        AND ws.set_type != 'warmup'
        AND wss.completed_at IS NOT NULL
        AND wss.started_at >= ?
        AND wss.started_at < ?
    `).get(WEEK_START_MS, WEEK_START_MS + 7 * 24 * 60 * 60 * 1000) as { vol: number };

    // Both completed sets (workout + GTG) contribute to volume
    expect(row.vol).toBe(650);
  });
});

// ── AC6 + AC20: GTG set → PR check passes ────────────────────────────────

describe("BLD-1088 AC6 + AC20 — GTG/variant PR: checkSetPR detects GTG set weight as a PR", () => {
  let db: InstanceType<typeof DatabaseSync>;

  beforeEach(() => {
    db = createTestDb();
    useDrizzleDb(db);
    db.prepare("INSERT INTO exercises (id, name) VALUES (?, ?)").run("ex-pull-up", "Pull-up");
  });

  it("AC6: checkSetPR returns true for a GTG set weight exceeding prior workout max", async () => {
    // Prior completed workout session with max weight 40 kg
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at)
                VALUES (?, 'workout', 'Old Workout', ?, ?)`).run(
      "old-sess", NOW_MS - 100000, NOW_MS - 50000
    );
    db.prepare(`INSERT INTO workout_sets (id, session_id, exercise_id, set_number, weight, reps, completed, set_type)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(
      "old-set", "old-sess", "ex-pull-up", 1, 40, 8, 1, "normal"
    );

    // New GTG session with weight 50 kg (new PR)
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date)
                VALUES (?, 'day_session', 'GTG: Pull-up', ?, ?, ?, ?)`).run(
      "gtg-sess", NOW_MS, NOW_MS, "ex-pull-up", "2026-05-10"
    );

    // checkSetPR checks if 50 > prior max (40) → should return true
    const isPR = await checkSetPR("ex-pull-up", 50, "gtg-sess");
    expect(isPR).toBe(true);
  });

  it("AC6: checkSetPR returns false for a GTG set weight NOT exceeding prior max", async () => {
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at)
                VALUES (?, 'workout', 'Old Workout', ?, ?)`).run(
      "old-sess2", NOW_MS - 100000, NOW_MS - 50000
    );
    db.prepare(`INSERT INTO workout_sets (id, session_id, exercise_id, set_number, weight, reps, completed, set_type)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(
      "old-set2", "old-sess2", "ex-pull-up", 1, 60, 8, 1, "normal"
    );

    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date)
                VALUES (?, 'day_session', 'GTG: Pull-up', ?, ?, ?, ?)`).run(
      "gtg-sess2", NOW_MS, NOW_MS, "ex-pull-up", "2026-05-10"
    );

    const isPR = await checkSetPR("ex-pull-up", 50, "gtg-sess2");
    expect(isPR).toBe(false);
  });

  it("AC20: when there is no prior history, checkSetPR returns false (no baseline to compare)", async () => {
    // No prior sessions for this exercise → checkSetPR returns false
    // (the PR comparison needs a prior max; first-ever set has no baseline)
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date)
                VALUES (?, 'day_session', 'GTG: Pull-up', ?, ?, ?, ?)`).run(
      "gtg-first", NOW_MS, NOW_MS, "ex-pull-up", "2026-05-10"
    );

    // No prior sessions for this exercise → no baseline → not a live PR (returns false)
    const isPR = await checkSetPR("ex-pull-up", 30, "gtg-first");
    expect(isPR).toBe(false);
  });

  it("AC20: a prior GTG session with higher weight prevents a new GTG set from being a PR", async () => {
    // Prior GTG session with max weight 80 kg (day_session, completed_at = started_at)
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date)
                VALUES (?, 'day_session', 'GTG: Pull-up', ?, ?, ?, ?)`).run(
      "gtg-prior", NOW_MS - 100000, NOW_MS - 100000, "ex-pull-up", "2026-05-09"
    );
    db.prepare(`INSERT INTO workout_sets (id, session_id, exercise_id, set_number, weight, reps, completed, set_type)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(
      "gtg-prior-set", "gtg-prior", "ex-pull-up", 1, 80, 5, 1, "normal"
    );

    // New GTG session with only 60 kg
    db.prepare(`INSERT INTO workout_sessions (id, kind, name, started_at, completed_at, day_session_exercise_id, day_session_date)
                VALUES (?, 'day_session', 'GTG: Pull-up', ?, ?, ?, ?)`).run(
      "gtg-new", NOW_MS, NOW_MS, "ex-pull-up", "2026-05-10"
    );

    const isPR = await checkSetPR("ex-pull-up", 60, "gtg-new");
    expect(isPR).toBe(false);
  });
});

// ── AC19: CSV import back-compat: missing kind treated as 'workout' ────────

describe("BLD-1088 AC19 — CSV round-trip: missing kind column treated as workout (back-compat)", () => {
  it("kind=null/undefined in imported session defaults to 'workout'", () => {
    // Simulates the CSV import logic: session.kind ?? "workout"
    // This is a pure logic test of the import contract defined in
    // lib/db/csv-import.ts:105 → `const kind = session.kind ?? "workout"`
    type CsvSessionRow = { kind?: string | null; id: string; name: string; started_at: number };

    function resolveKind(session: CsvSessionRow): string {
      return session.kind ?? "workout";
    }

    // Old export without kind column → missing field → defaults to 'workout'
    expect(resolveKind({ id: "1", name: "Leg Day", started_at: 1000 })).toBe("workout");
    expect(resolveKind({ id: "2", name: "Leg Day", started_at: 1000, kind: null })).toBe("workout");
    expect(resolveKind({ id: "3", name: "Leg Day", started_at: 1000, kind: undefined })).toBe("workout");

    // Export with explicit kind → preserved
    expect(resolveKind({ id: "4", name: "GTG", started_at: 1000, kind: "day_session" })).toBe("day_session");
    expect(resolveKind({ id: "5", name: "Normal", started_at: 1000, kind: "workout" })).toBe("workout");
  });

  it("day_session kind survives round-trip: kind field preserved in CSV export structure", () => {
    // Simulates lib/db/csv.ts export shape for WorkoutCSVRow
    type WorkoutCSVRow = {
      session_id: string;
      kind: string | null;
      day_session_date: string | null;
    };

    // Two session rows — one workout, one day_session
    const csvRows: WorkoutCSVRow[] = [
      { session_id: "sess-1", kind: "workout", day_session_date: null },
      { session_id: "sess-2", kind: "day_session", day_session_date: "2026-05-10" },
    ];

    // After round-trip: kind is preserved
    const workoutRows = csvRows.filter(r => (r.kind ?? "workout") === "workout");
    const daySessionRows = csvRows.filter(r => r.kind === "day_session");

    expect(workoutRows).toHaveLength(1);
    expect(workoutRows[0].session_id).toBe("sess-1");
    expect(daySessionRows).toHaveLength(1);
    expect(daySessionRows[0].day_session_date).toBe("2026-05-10");
  });

  it("back-compat: old exports (no kind field) produce only kind='workout' rows on re-import", () => {
    // Simulate a batch of CSV rows from an old export without kind field
    const oldExportRows = [
      { session_id: "a", name: "Push Day" },
      { session_id: "b", name: "Pull Day" },
      { session_id: "c", name: "Leg Day" },
    ] as Array<{ session_id: string; name: string; kind?: string | null }>;

    const importedKinds = oldExportRows.map(r => r.kind ?? "workout");
    expect(importedKinds).toEqual(["workout", "workout", "workout"]);
  });
});
