import { compileMessageOrThrow } from "@lingui/message-utils/compileMessage";
import type { Catalog } from "./catalog-io";

export const RUNTIME_LOCALES = ["en-US", "en-GB", "zh-TW", "zh-CN"] as const;

function message(value: Catalog[string]): string {
  return typeof value === "string" ? value : value.message;
}

export function renderRuntimeCatalogs(catalogs: Record<string, Catalog>): string {
  const compiled = Object.fromEntries(
    RUNTIME_LOCALES.map((locale) => [
      locale,
      Object.fromEntries(
        Object.entries(catalogs[locale]).map(([id, entry]) => {
          try {
            return [id, compileMessageOrThrow(message(entry))];
          } catch (error) {
            const detail = error instanceof Error ? error.message : String(error);
            throw new Error(`${locale}:${id}: ${detail}`);
          }
        })
      ),
    ])
  );

  return [
    "// Generated by npm run i18n:runtime:gen. Do not edit.",
    'import type { Messages } from "@lingui/core";',
    'import type { SupportedLocale } from "./locales";',
    "",
    `export const COMPILED_CATALOGS = ${JSON.stringify(compiled)} as unknown as Record<SupportedLocale, Messages>;`,
    "",
  ].join("\n");
}
