// AUTO-GENERATED by scripts/generate-changelog.ts from CHANGELOG.md.
// Do not edit by hand — run `npm run changelog:gen` to refresh.

export interface ReleaseEntry {
  version: string;
  date: string | null;
  versionCode: number | null;
  body: string;
}

export const CHANGELOG: ReleaseEntry[] = [
  {
    "version": "0.26.12",
    "date": "2026-04-26",
    "versionCode": 65,
    "body": "- Web: fixed a crash on the Summary screen and other queries that returned larger result sets — the SQLite worker was truncating its length prefix to one byte, corrupting any payload ≥256 bytes (BLD-660).\n- Workout history: heatmap now renders in a stable 7-column grid at every screen width — Sundays no longer wrap to a new row at narrow widths (BLD-661).\n- Workout history: heatmap, streak, and dot map now populate correctly from seeded sessions — timestamps are stored in milliseconds end-to-end (BLD-662).\n- Workout history: streak card labels clarified to make current vs longest streak unambiguous (BLD-663)."
  },
  {
    "version": "0.26.8",
    "date": "2026-04-24",
    "versionCode": 57,
    "body": "- Set-completion now confirms with a subtle haptic + audio cue — toggle separately from timer sounds in Settings → Preferences.\n- Previous-performance chip on the session screen now looks tappable again (affordance restored).\n- Adaptive rest timer now shows a \"+N\" overflow counter when the chip truncates.\n- Strava auth errors surface a proper toast with a \"Get help\" CTA.\n- Session screen performance pass: memoization + background-timer pause when the app is backgrounded."
  },
  {
    "version": "0.26.7",
    "date": "2026-04-24",
    "versionCode": null,
    "body": "- Adaptive rest timer — intelligently suggests rest duration based on your recent set intensity.\n- End-to-end visual regression suite now uses a deterministic exercise fixture.\n- Bundle-gate CI check now runs on every PR so the required status always reports.\n- F-Droid `versionCode` sync fix — updates now install cleanly without the \"Installed\" ghost."
  },
  {
    "version": "0.26.6",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Workouts tab now shows a more welcoming empty state when you have no sessions yet.\n- New subtle severity + heatmap theme tokens for a calmer progress view.\n- Strava connection actions emit Sentry breadcrumbs for faster triage of auth hiccups."
  },
  {
    "version": "0.26.5",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Body profile unit labels now refresh immediately when you change weight/measurement units in Settings.\n- Strava configuration errors now surface a tappable \"Get help\" CTA in the toast.\n- Removed the one-time post-BLD-485 reinstall banner now that the keystore transition is complete."
  },
  {
    "version": "0.26.4",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- PR dashboard empty state now has a friendly retry button instead of a blank screen on fetch failure.\n- Post-workout summary: Android hardware back is now intercepted so you don't accidentally drop out of the rating flow.\n- Typography polish on the PR stats row.\n- First release signed with the new persistent production keystore (future updates install cleanly in place)."
  }
];
