// AUTO-GENERATED by scripts/generate-changelog.ts from CHANGELOG.md.
// Do not edit by hand — run `npm run changelog:gen` to refresh.

export interface ReleaseEntry {
  version: string;
  date: string | null;
  versionCode: number | null;
  body: string;
}

export const CHANGELOG: ReleaseEntry[] = [
  {
    "version": "0.26.33",
    "date": "2026-05-12",
    "versionCode": 103,
    "body": "- **Advanced set schemes (analytics)**: rest-pause, cluster, and myo-rep sets now contribute correct volume and e1RM values to all analytics surfaces (weekly/monthly trends, exercise history bests, achievements). Previously, multi-segment sets were excluded or under-counted due to the reps ≤ 12 filter.\n- **Adaptive Macro Coach** (off by default): Enable in Settings → Nutrition → Adaptive Macro Coach to get a weekly advisory card that suggests a calorie target based on your trend weight and average intake over the past two weeks. The coach is advisory only — your target is never changed without your tap. Includes a hard safety floor (based on your sex and estimated metabolic rate), a ±300 kcal/week cap, Right Why check-in, and a one-tap one-month pause.\n- **Tempo Coach (haptic engine)**: Enable \"Tempo Coach\" in Settings → Preferences to get a haptic rep guide during your sets. When active, a vibration cues each phase of your tempo (eccentric → bottom pause → concentric → top pause) in real time. A compact overlay shows the current phase and lets you stop the coach at any time. The coach auto-stops when the set is logged and cancels if you background the app."
  },
  {
    "version": "0.26.32",
    "date": "2026-05-11",
    "versionCode": 102,
    "body": "- **Form Check Comparison**: Compare form clips side-by-side from the Form Library or from the clip player with synchronized play/pause/reset, A↔B swap, in-sheet clip picker, and landscape layout support.\n- **Tempo Coach (data layer)**: Set a per-exercise default tempo (e.g. `3-1-2-0`), which auto-fills on every new set for that exercise. Edit tempo per-set via the new Set Options sheet. Tempo is preserved across CSV import/export and template initialization."
  },
  {
    "version": "0.26.31",
    "date": "2026-05-11",
    "versionCode": 101,
    "body": "- **Settings cleanup**: Removed the Health Connect integration entry from Settings. The feature was never fully functional; removing it reduces permission surface and eliminates a confusing toggle for Android users.\n- **Database cleanup**: Removed the legacy `health_connect_sync_log` database table and its associated app_settings key on device upgrade. New installs are not affected.\n- **Smart Rest Coach (fix)**: Live countdown and scheduled rest notifications now correctly resume after the app is force-quit and reopened mid-rest on Android. Previously, OS-scheduled notifications could be lost on process kill; they are now re-scheduled on cold-start resume.\n- **Session Pacing**: Post-session summary now includes an **Estimated pacing** card showing a stacked bar with time spent Working, Resting, and in Other (transition/setup) time. Tap the card to see a per-exercise breakdown table. Working time for rep-based sets is estimated at ~2 s/rep; rest is the gap between consecutive sets on the same exercise (capped at 10 min). Available on completed sessions only. Pacing duration now matches the session duration shown in the summary header.\n- **Session Pacing (fix)**: Pacing totals now correctly align with the session duration shown in the summary header; the breakdown sheet tap interaction is restored on all devices."
  },
  {
    "version": "0.26.30",
    "date": "2026-05-10",
    "versionCode": 100,
    "body": "- **Connect Strava (fix)**: The \"Connect Strava\" button in Settings → Integrations now actually works. Previously it always failed silently with an \"invalid redirect URI\" error from Strava's side. The OAuth flow now correctly hands off through a small HTTPS bouncer back to the app."
  },
  {
    "version": "0.26.29",
    "date": "2026-05-10",
    "versionCode": 99,
    "body": "- **Smart Rest Coach**: Rest-timer notifications now include a pre-end cue (5–20s before rest ends), a live lock-screen countdown that updates every 5 seconds (Android), and an optional next-set preview showing exercise, target weight, and rep range right on the notification — so you never need to unlock the phone just to remember what's next. All three features are individually togglable under Settings → Rest Timer.\n- **Stack marker quick-pick**: Cable exercises at calibrated gyms now show a marker pill instead of a numeric weight field. Tap to pick your stack position; the true weight is resolved automatically. Long-press to fall back to numeric entry on any set.\n- **Stack marker hint**: Cable exercises at gyms without saved calibration now show a one-time, dismissible hint pointing to where to add stack calibration so future sessions can use marker quick-pick.\n- **Marker autofill reliability**: First add-set after switching gyms now consistently fills in the right stack marker instead of occasionally dropping back to numeric entry.\n- **Bug fix — marker/weight save reliability**: On rare DB write failures when logging a stack marker or manual weight, the set row now correctly reverts to its previous state instead of showing stale or blank values."
  },
  {
    "version": "0.26.28",
    "date": "2026-05-10",
    "versionCode": 98,
    "body": "- **Plateau detection & break-through suggestions**: When an exercise stalls for 4+ sessions without weight or rep improvement, a suggestion card surfaces on the exercise detail screen with a context-aware action — deload to break a loaded stall, push for +2 reps at current weight, or check form if effort has been creeping up (BLD-1122).\n- **Settings scroll fix (follow-up)**: Increased the bottom clearance buffer on the Settings screen to prevent the About section and links from being clipped behind the floating tab bar on Z Fold6 and other foldable or tall-nav Android devices (BLD-1124).\n\n- **Track pulley pin position**: Tap the new pin chip next to any cable set to record which pulley pin you used (1 through your machine's max). Stored per set so your exact stack position is always in the history export (BLD-1114).\n- **Setup photo per set**: Tap the camera icon on any completed cable set to snap a quick photo of the cable path, attachment, and pin — a visual reference so you can replicate the exact setup next time (BLD-1114).\n- **RPE capture nudge**: Exercise detail now shows a one-time banner for users who have logged RPE before but haven't enabled live capture — tap \"Turn on\" to enable in one step, or \"Not now\" to dismiss forever (BLD-1117)."
  },
  {
    "version": "0.26.27",
    "date": "2026-05-09",
    "versionCode": 97,
    "body": "- **Record directly from Form tab**: Tap the new \"Record clip\" button in the Form clips tab (exercise detail drawer) to record a new clip without leaving the exercise view. The button auto-targets the most recent unclipped set, or shows a helper hint when all sets already have clips (BLD-1105).\n- **Replace or delete individual clips**: Each clip row in the Form clips tab now has an overflow menu (⋯) with Replace and Delete actions. Replace atomically swaps the file and database row in a single transaction (BLD-1105).\n- **Manage all clips from Settings**: The Form Clips card in Settings is now tappable and opens a full clip library grouped by exercise. Delete individual clips or bulk-delete all clips to reclaim storage instantly (BLD-1105).\n- **Settings scroll fix**: Fixed settings screen content cut off behind the floating tab bar on tall Android devices (Galaxy Z Fold6, Pixel 7 Pro) — the About section and links at the bottom are now fully accessible (BLD-1106)\n- **Live RPE capture**: Rate each set's effort with a tap (Easy / Moderate / Hard / Max) directly in the workout screen. Long-press for a precise value (6.0–10.0). RPE powers the smart rest timer and next-set suggestion — enable in Settings (BLD-1110)."
  },
  {
    "version": "0.26.26",
    "date": "2026-05-09",
    "versionCode": 96,
    "body": "- **Smart Rest Timer**: Rest suggestions now adapt to each exercise based on your actual median rest over the last 30 days. Pin a custom default per exercise, or let the timer learn automatically — templates and 90 s fallback remain for new users (BLD-1100)."
  },
  {
    "version": "0.26.25",
    "date": "2026-05-08",
    "versionCode": 95,
    "body": "- **Database upgrade fix**: Resolved a crash on first launch (\"Database error: no such column: gym_id\") that affected users upgrading from a much older install. Migration ordering is now phased to prevent this class of bug from recurring."
  },
  {
    "version": "0.26.24",
    "date": "2026-05-08",
    "versionCode": 94,
    "body": "- **Form Check Videos**: Record short video clips (up to 15 s) on each completed working set to review technique over time. Clips are stored locally only — never uploaded, never backed up to iCloud/Google (BLD-1092).\n- **Form Library**: \"Form clips\" tab in the exercise detail drawer shows all clips for an exercise reverse-chronologically with date, weight, and reps overlay (BLD-1092).\n- **Side-by-side comparison**: Compare any two form clips from your library in a split-screen view (BLD-1092).\n- **Storage panel**: Settings → Storage shows total clip size and count with a \"Manage\" shortcut (BLD-1092).\n- **Privacy**: form-clips/ directory excluded from iOS iCloud and Android Auto Backup via Expo config plugin — form-check videos stay on-device only (BLD-1095).\n- **Database integrity**: Enabled SQLite foreign-key enforcement on every connection so historic delete paths (workout history, CSV import undo, in-progress cancel) now correctly clean up Strava and Health Connect sync-log entries instead of leaving orphan rows.\n- **Grease-the-Groove mode**: Log scattered sets throughout the day without starting a workout — tap the floating Quick Add button, pick an exercise, confirm reps/weight, and get a 4-second undo toast. Daily GTG totals appear as a summary card on the home screen and a light-fill dot on the calendar."
  },
  {
    "version": "0.26.23",
    "date": "2026-05-08",
    "versionCode": 93,
    "body": "### New features\n- **Per-variant PR cards for cable exercises** — strength records now track each cable exercise variant separately so PRs reflect the actual movement you trained (BLD-1086).\n- **Per-Gym Cable Stack Calibration** — calibrate each gym's cable stack once and have plate math + load suggestions follow you between gyms (BLD-1060).\n- **Pinned per-exercise notes** — pin a note to any exercise so it surfaces every time you start that exercise in a session (BLD-1028).\n- **Curated Programs Library** — bundled r/bodyweightfitness Recommended Routine v1 as a starter program; more curated programs to follow.\n- **Export workout templates** — long-press a template to export it for sharing or backup.\n- **Template sync from completed sessions** — edits made to sets during a session now flow back into the source template on completion (BLD-1031).\n- **128-exercise Gemini illustration set** — refreshed exercise illustrations using the new Gemini-generated set, retiring the older gpt-image-1 voltra subset (BLD-989).\n\n### Fixes\n- **History filter chips scroll correctly** — bounded the FilterBar container so the chip row actually scrolls instead of clipping.\n- **Set numbering after delete** — deleting a set in a session now renumbers the remaining sets correctly (BLD-1044).\n- **Body view padding** — Progress > Body list no longer hides its last row behind the floating tab bar (BLD-990).\n- **Tablet home layout** — workout cards no longer get cropped on tablet flex-wrap rows (BLD-1011).\n- **Monthly share button** — Progress > Monthly view share button no longer overlaps the floating navbar."
  },
  {
    "version": "0.26.22",
    "date": "2026-05-03",
    "versionCode": 92,
    "body": "- Internal/CI: regression-catcher fixture migrated to wrapper-fixture pattern (BLD-1023)."
  },
  {
    "version": "0.26.21",
    "date": "2026-05-03",
    "versionCode": 91,
    "body": "- Internal/CI: routine release — no user-facing changes."
  },
  {
    "version": "0.26.20",
    "date": "2026-05-02",
    "versionCode": 90,
    "body": "### Added\n- Hydration tracking — log water in ml or fl oz from the Nutrition tab; configurable daily goal and preset volumes in Settings.\n- Workout templates now remember the training mode you pick per Voltra exercise; sessions started from the template open in the saved mode automatically.\n\n### Changed\n- Workout duration now starts when you log your first completed set, not the moment you tap Start (BLD-630).\n\n### Removed\n- Removed the **Eccentric** training mode chip and tempo tracking. Existing eccentric sets in your history are preserved as standard sets; other Voltra modes (Band, Damper, Isokinetic, Isometric, Custom, Rowing) are unchanged.\n\n### Internal/CI\n- Merge gate: comment-fallback approvals for lenient branch protection."
  },
  {
    "version": "0.26.19",
    "date": "2026-05-01",
    "versionCode": 76,
    "body": "- Fixed Android crash on app open caused by WearOS module class-loading failure on devices without Google Play Services.\n- Replaced direct WearOS Wearable API import with Class.forName() reflection to prevent NoClassDefFoundError at startup.\n- Removed WearOSModule from Expo autolinker to prevent F-Droid build crashes.\n- Added Android emulator smoke test to CI pipeline to catch launch crashes before release."
  },
  {
    "version": "0.26.12",
    "date": "2026-04-26",
    "versionCode": 65,
    "body": "- Web: fixed a crash on the Summary screen and other queries that returned larger result sets — the SQLite worker was truncating its length prefix to one byte, corrupting any payload ≥256 bytes (BLD-660).\n- Workout history: heatmap now renders in a stable 7-column grid at every screen width — Sundays no longer wrap to a new row at narrow widths (BLD-661).\n- Workout history: heatmap, streak, and dot map now populate correctly from seeded sessions — timestamps are stored in milliseconds end-to-end (BLD-662).\n- Workout history: streak card labels clarified to make current vs longest streak unambiguous (BLD-663)."
  },
  {
    "version": "0.26.8",
    "date": "2026-04-24",
    "versionCode": 57,
    "body": "- Set-completion now confirms with a subtle haptic + audio cue — toggle separately from timer sounds in Settings → Preferences.\n- Previous-performance chip on the session screen now looks tappable again (affordance restored).\n- Adaptive rest timer now shows a \"+N\" overflow counter when the chip truncates.\n- Strava auth errors surface a proper toast with a \"Get help\" CTA.\n- Session screen performance pass: memoization + background-timer pause when the app is backgrounded."
  },
  {
    "version": "0.26.7",
    "date": "2026-04-24",
    "versionCode": null,
    "body": "- Adaptive rest timer — intelligently suggests rest duration based on your recent set intensity.\n- End-to-end visual regression suite now uses a deterministic exercise fixture.\n- Bundle-gate CI check now runs on every PR so the required status always reports.\n- F-Droid `versionCode` sync fix — updates now install cleanly without the \"Installed\" ghost."
  },
  {
    "version": "0.26.6",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Workouts tab now shows a more welcoming empty state when you have no sessions yet.\n- New subtle severity + heatmap theme tokens for a calmer progress view.\n- Strava connection actions emit Sentry breadcrumbs for faster triage of auth hiccups."
  },
  {
    "version": "0.26.5",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Body profile unit labels now refresh immediately when you change weight/measurement units in Settings.\n- Strava configuration errors now surface a tappable \"Get help\" CTA in the toast.\n- Removed the one-time post-BLD-485 reinstall banner now that the keystore transition is complete."
  },
  {
    "version": "0.26.4",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- PR dashboard empty state now has a friendly retry button instead of a blank screen on fetch failure.\n- Post-workout summary: Android hardware back is now intercepted so you don't accidentally drop out of the rating flow.\n- Typography polish on the PR stats row.\n- First release signed with the new persistent production keystore (future updates install cleanly in place)."
  }
];
