// AUTO-GENERATED by scripts/generate-changelog.ts from CHANGELOG.md.
// Do not edit by hand — run `npm run changelog:gen` to refresh.

export interface ReleaseEntry {
  version: string;
  date: string | null;
  versionCode: number | null;
  body: string;
}

export const CHANGELOG: ReleaseEntry[] = [
  {
    "version": "0.26.24",
    "date": "2026-05-08",
    "versionCode": 94,
    "body": "- **Form Check Videos**: Record short video clips (up to 15 s) on each completed working set to review technique over time. Clips are stored locally only — never uploaded, never backed up to iCloud/Google (BLD-1092).\n- **Form Library**: \"Form clips\" tab in the exercise detail drawer shows all clips for an exercise reverse-chronologically with date, weight, and reps overlay (BLD-1092).\n- **Side-by-side comparison**: Compare any two form clips from your library in a split-screen view (BLD-1092).\n- **Storage panel**: Settings → Storage shows total clip size and count with a \"Manage\" shortcut (BLD-1092).\n- **Privacy**: form-clips/ directory excluded from iOS iCloud and Android Auto Backup via Expo config plugin — form-check videos stay on-device only (BLD-1095).\n- **Database integrity**: Enabled SQLite foreign-key enforcement on every connection so historic delete paths (workout history, CSV import undo, in-progress cancel) now correctly clean up Strava and Health Connect sync-log entries instead of leaving orphan rows.\n- **Grease-the-Groove mode**: Log scattered sets throughout the day without starting a workout — tap the floating Quick Add button, pick an exercise, confirm reps/weight, and get a 4-second undo toast. Daily GTG totals appear as a summary card on the home screen and a light-fill dot on the calendar."
  },
  {
    "version": "0.26.23",
    "date": "2026-05-08",
    "versionCode": 93,
    "body": "### New features\n- **Per-variant PR cards for cable exercises** — strength records now track each cable exercise variant separately so PRs reflect the actual movement you trained (BLD-1086).\n- **Per-Gym Cable Stack Calibration** — calibrate each gym's cable stack once and have plate math + load suggestions follow you between gyms (BLD-1060).\n- **Pinned per-exercise notes** — pin a note to any exercise so it surfaces every time you start that exercise in a session (BLD-1028).\n- **Curated Programs Library** — bundled r/bodyweightfitness Recommended Routine v1 as a starter program; more curated programs to follow.\n- **Export workout templates** — long-press a template to export it for sharing or backup.\n- **Template sync from completed sessions** — edits made to sets during a session now flow back into the source template on completion (BLD-1031).\n- **128-exercise Gemini illustration set** — refreshed exercise illustrations using the new Gemini-generated set, retiring the older gpt-image-1 voltra subset (BLD-989).\n\n### Fixes\n- **History filter chips scroll correctly** — bounded the FilterBar container so the chip row actually scrolls instead of clipping.\n- **Set numbering after delete** — deleting a set in a session now renumbers the remaining sets correctly (BLD-1044).\n- **Body view padding** — Progress > Body list no longer hides its last row behind the floating tab bar (BLD-990).\n- **Tablet home layout** — workout cards no longer get cropped on tablet flex-wrap rows (BLD-1011).\n- **Monthly share button** — Progress > Monthly view share button no longer overlaps the floating navbar."
  },
  {
    "version": "0.26.22",
    "date": "2026-05-03",
    "versionCode": 92,
    "body": "- Internal/CI: regression-catcher fixture migrated to wrapper-fixture pattern (BLD-1023)."
  },
  {
    "version": "0.26.21",
    "date": "2026-05-03",
    "versionCode": 91,
    "body": "- Internal/CI: routine release — no user-facing changes."
  },
  {
    "version": "0.26.20",
    "date": "2026-05-02",
    "versionCode": 90,
    "body": "### Added\n- Hydration tracking — log water in ml or fl oz from the Nutrition tab; configurable daily goal and preset volumes in Settings.\n- Workout templates now remember the training mode you pick per Voltra exercise; sessions started from the template open in the saved mode automatically.\n\n### Changed\n- Workout duration now starts when you log your first completed set, not the moment you tap Start (BLD-630).\n\n### Removed\n- Removed the **Eccentric** training mode chip and tempo tracking. Existing eccentric sets in your history are preserved as standard sets; other Voltra modes (Band, Damper, Isokinetic, Isometric, Custom, Rowing) are unchanged.\n\n### Internal/CI\n- Merge gate: comment-fallback approvals for lenient branch protection."
  },
  {
    "version": "0.26.19",
    "date": "2026-05-01",
    "versionCode": 76,
    "body": "- Fixed Android crash on app open caused by WearOS module class-loading failure on devices without Google Play Services.\n- Replaced direct WearOS Wearable API import with Class.forName() reflection to prevent NoClassDefFoundError at startup.\n- Removed WearOSModule from Expo autolinker to prevent F-Droid build crashes.\n- Added Android emulator smoke test to CI pipeline to catch launch crashes before release."
  },
  {
    "version": "0.26.12",
    "date": "2026-04-26",
    "versionCode": 65,
    "body": "- Web: fixed a crash on the Summary screen and other queries that returned larger result sets — the SQLite worker was truncating its length prefix to one byte, corrupting any payload ≥256 bytes (BLD-660).\n- Workout history: heatmap now renders in a stable 7-column grid at every screen width — Sundays no longer wrap to a new row at narrow widths (BLD-661).\n- Workout history: heatmap, streak, and dot map now populate correctly from seeded sessions — timestamps are stored in milliseconds end-to-end (BLD-662).\n- Workout history: streak card labels clarified to make current vs longest streak unambiguous (BLD-663)."
  },
  {
    "version": "0.26.8",
    "date": "2026-04-24",
    "versionCode": 57,
    "body": "- Set-completion now confirms with a subtle haptic + audio cue — toggle separately from timer sounds in Settings → Preferences.\n- Previous-performance chip on the session screen now looks tappable again (affordance restored).\n- Adaptive rest timer now shows a \"+N\" overflow counter when the chip truncates.\n- Strava auth errors surface a proper toast with a \"Get help\" CTA.\n- Session screen performance pass: memoization + background-timer pause when the app is backgrounded."
  },
  {
    "version": "0.26.7",
    "date": "2026-04-24",
    "versionCode": null,
    "body": "- Adaptive rest timer — intelligently suggests rest duration based on your recent set intensity.\n- End-to-end visual regression suite now uses a deterministic exercise fixture.\n- Bundle-gate CI check now runs on every PR so the required status always reports.\n- F-Droid `versionCode` sync fix — updates now install cleanly without the \"Installed\" ghost."
  },
  {
    "version": "0.26.6",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Workouts tab now shows a more welcoming empty state when you have no sessions yet.\n- New subtle severity + heatmap theme tokens for a calmer progress view.\n- Strava connection actions emit Sentry breadcrumbs for faster triage of auth hiccups."
  },
  {
    "version": "0.26.5",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- Body profile unit labels now refresh immediately when you change weight/measurement units in Settings.\n- Strava configuration errors now surface a tappable \"Get help\" CTA in the toast.\n- Removed the one-time post-BLD-485 reinstall banner now that the keystore transition is complete."
  },
  {
    "version": "0.26.4",
    "date": "2026-04-23",
    "versionCode": null,
    "body": "- PR dashboard empty state now has a friendly retry button instead of a blank screen on fetch failure.\n- Post-workout summary: Android hardware back is now intercepted so you don't accidentally drop out of the rating flow.\n- Typography polish on the PR stats row.\n- First release signed with the new persistent production keystore (future updates install cleanly in place)."
  }
];
