import type { Exercise } from "./types";

let counter = 0;
function id(): string {
  counter++;
  return `seed-${counter.toString().padStart(3, "0")}`;
}

export function seedExercises(): Exercise[] {
  counter = 0;
  return [
    // ── Chest (8) ──────────────────────────────────────────
    {
      id: id(),
      name: "Bench Press (Barbell)",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["triceps", "shoulders"],
      equipment: "barbell",
      instructions:
        "1. Lie on a flat bench with feet flat on the floor.\n2. Grip the bar slightly wider than shoulder-width.\n3. Unrack the bar and lower it to your mid-chest.\n4. Press the bar back up until arms are fully extended.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Incline Dumbbell Press",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["shoulders", "triceps"],
      equipment: "dumbbell",
      instructions:
        "1. Set a bench to a 30–45 degree incline.\n2. Hold a dumbbell in each hand at shoulder level.\n3. Press the dumbbells upward until arms are extended.\n4. Lower the dumbbells back to shoulder level.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Push-ups",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["triceps", "shoulders", "core"],
      equipment: "bodyweight",
      instructions:
        "1. Start in a plank position with hands shoulder-width apart.\n2. Lower your body until your chest nearly touches the floor.\n3. Push through your palms to return to the starting position.\n4. Keep your core tight and body in a straight line throughout.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Cable Fly",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["shoulders"],
      equipment: "cable",
      instructions:
        "1. Set the cable pulleys to shoulder height.\n2. Grab the handles and step forward into a staggered stance.\n3. With a slight bend in your elbows, bring your hands together in front of your chest.\n4. Slowly return your arms to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dips (Chest)",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["triceps", "shoulders"],
      equipment: "bodyweight",
      instructions:
        "1. Mount the dip bars and lean your torso slightly forward.\n2. Lower your body by bending your elbows until you feel a stretch in your chest.\n3. Press back up to the starting position.\n4. Keep the forward lean to emphasize chest engagement.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dumbbell Fly",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["shoulders"],
      equipment: "dumbbell",
      instructions:
        "1. Lie on a flat bench holding dumbbells above your chest with arms extended.\n2. With a slight bend in the elbows, lower the dumbbells out to the sides.\n3. Lower until you feel a stretch in your chest.\n4. Squeeze your chest to bring the dumbbells back together.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Machine Chest Press",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["triceps", "shoulders"],
      equipment: "machine",
      instructions:
        "1. Sit in the chest press machine and adjust the seat height.\n2. Grip the handles at chest level.\n3. Press the handles forward until arms are extended.\n4. Slowly return to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Decline Bench Press",
      category: "chest",
      primary_muscles: ["chest"],
      secondary_muscles: ["triceps", "shoulders"],
      equipment: "barbell",
      instructions:
        "1. Lie on a decline bench and secure your legs.\n2. Grip the bar slightly wider than shoulder-width.\n3. Unrack the bar and lower it to your lower chest.\n4. Press the bar back up until arms are fully extended.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },

    // ── Back (10) ──────────────────────────────────────────
    {
      id: id(),
      name: "Deadlift",
      category: "back",
      primary_muscles: ["back", "hamstrings", "glutes"],
      secondary_muscles: ["core", "traps", "forearms"],
      equipment: "barbell",
      instructions:
        "1. Stand with feet hip-width apart, barbell over mid-foot.\n2. Bend at the hips and knees to grip the bar.\n3. Keep your back flat and chest up.\n4. Drive through your heels to stand up, pulling the bar along your legs.\n5. Lower the bar back to the floor with control.",
      difficulty: "advanced",
      is_custom: false,
    },
    {
      id: id(),
      name: "Barbell Row",
      category: "back",
      primary_muscles: ["back", "lats"],
      secondary_muscles: ["biceps", "forearms", "traps"],
      equipment: "barbell",
      instructions:
        "1. Stand with feet shoulder-width apart, knees slightly bent.\n2. Hinge at the hips and grip the barbell with an overhand grip.\n3. Pull the bar to your lower chest, squeezing your shoulder blades.\n4. Lower the bar back to arm's length.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Pull-ups",
      category: "back",
      primary_muscles: ["lats", "back"],
      secondary_muscles: ["biceps", "forearms"],
      equipment: "bodyweight",
      instructions:
        "1. Hang from a pull-up bar with an overhand grip, hands wider than shoulders.\n2. Pull your body up until your chin clears the bar.\n3. Lower yourself back to a full hang with control.\n4. Keep your core engaged throughout the movement.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Lat Pulldown",
      category: "back",
      primary_muscles: ["lats"],
      secondary_muscles: ["biceps", "back"],
      equipment: "cable",
      instructions:
        "1. Sit at the lat pulldown machine and grip the bar wide.\n2. Pull the bar down to your upper chest.\n3. Squeeze your shoulder blades at the bottom.\n4. Slowly return the bar to the top.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Seated Cable Row",
      category: "back",
      primary_muscles: ["back", "lats"],
      secondary_muscles: ["biceps", "forearms"],
      equipment: "cable",
      instructions:
        "1. Sit at the cable row station with feet on the platform.\n2. Grip the handle and sit upright.\n3. Pull the handle to your abdomen, squeezing your back.\n4. Slowly extend your arms back to the start.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "T-Bar Row",
      category: "back",
      primary_muscles: ["back", "lats"],
      secondary_muscles: ["biceps", "traps"],
      equipment: "barbell",
      instructions:
        "1. Straddle the T-bar or landmine bar.\n2. Grip the handles and hinge forward at the hips.\n3. Pull the bar up to your chest.\n4. Lower it back with control.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dumbbell Row",
      category: "back",
      primary_muscles: ["back", "lats"],
      secondary_muscles: ["biceps", "forearms"],
      equipment: "dumbbell",
      instructions:
        "1. Place one knee and hand on a bench for support.\n2. Hold a dumbbell in the opposite hand.\n3. Pull the dumbbell to your hip, squeezing your back.\n4. Lower the dumbbell with control.\n5. Repeat for the desired number of reps on each side.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Face Pull",
      category: "back",
      primary_muscles: ["back", "shoulders"],
      secondary_muscles: ["traps"],
      equipment: "cable",
      instructions:
        "1. Set a cable pulley to upper chest height with a rope attachment.\n2. Grip the rope with both hands, palms facing each other.\n3. Pull the rope toward your face, flaring elbows out.\n4. Squeeze your rear delts and upper back.\n5. Slowly return to the start and repeat.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Chin-ups",
      category: "back",
      primary_muscles: ["lats", "biceps"],
      secondary_muscles: ["back", "forearms"],
      equipment: "bodyweight",
      instructions:
        "1. Hang from a bar with a supinated (underhand) grip, hands shoulder-width.\n2. Pull your body up until your chin clears the bar.\n3. Lower yourself back to a full hang.\n4. Keep your core engaged and avoid swinging.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Hyperextension",
      category: "back",
      primary_muscles: ["back", "glutes"],
      secondary_muscles: ["hamstrings"],
      equipment: "bodyweight",
      instructions:
        "1. Position yourself face down on a hyperextension bench.\n2. Cross your arms over your chest or behind your head.\n3. Lower your upper body toward the floor.\n4. Raise your torso until your body forms a straight line.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },

    // ── Shoulders (8) ──────────────────────────────────────
    {
      id: id(),
      name: "Overhead Press",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["triceps", "core"],
      equipment: "barbell",
      instructions:
        "1. Stand with feet shoulder-width apart, barbell at shoulder height.\n2. Press the bar overhead until arms are fully extended.\n3. Lower the bar back to shoulder height.\n4. Keep your core braced throughout.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Lateral Raise",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["traps"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with dumbbells at your sides.\n2. Raise the dumbbells out to the sides until arms are parallel to the floor.\n3. Keep a slight bend in your elbows.\n4. Lower the dumbbells back to your sides.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Front Raise",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["chest"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with dumbbells in front of your thighs.\n2. Raise one or both dumbbells in front of you to shoulder height.\n3. Keep a slight bend in your elbows.\n4. Lower the dumbbells back down with control.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Rear Delt Fly",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["back", "traps"],
      equipment: "dumbbell",
      instructions:
        "1. Bend forward at the hips with dumbbells hanging below.\n2. Raise the dumbbells out to the sides, squeezing your rear delts.\n3. Keep a slight bend in your elbows.\n4. Lower the dumbbells with control.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Arnold Press",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["triceps"],
      equipment: "dumbbell",
      instructions:
        "1. Sit on a bench with dumbbells at shoulder height, palms facing you.\n2. Press the dumbbells overhead while rotating your palms to face forward.\n3. Reverse the rotation as you lower the dumbbells.\n4. Return to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Upright Row",
      category: "shoulders",
      primary_muscles: ["shoulders", "traps"],
      secondary_muscles: ["biceps"],
      equipment: "barbell",
      instructions:
        "1. Stand with a barbell held in front of your thighs, narrow grip.\n2. Pull the bar straight up along your body to chin height.\n3. Keep your elbows higher than your wrists.\n4. Lower the bar with control.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Rear Delt Face Pull",
      category: "shoulders",
      primary_muscles: ["shoulders"],
      secondary_muscles: ["traps", "back"],
      equipment: "cable",
      instructions:
        "1. Set a cable to upper chest height with a rope attachment.\n2. Pull the rope toward your face with elbows high.\n3. Externally rotate your shoulders at the end.\n4. Slowly return to the start.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Shrugs",
      category: "shoulders",
      primary_muscles: ["traps"],
      secondary_muscles: ["shoulders"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with dumbbells at your sides.\n2. Shrug your shoulders up toward your ears.\n3. Hold briefly at the top.\n4. Lower your shoulders back down.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },

    // ── Biceps (6) ─────────────────────────────────────────
    {
      id: id(),
      name: "Barbell Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "barbell",
      instructions:
        "1. Stand with a barbell held at arm's length, underhand grip.\n2. Curl the bar up to shoulder level by bending your elbows.\n3. Keep your upper arms stationary.\n4. Lower the bar back to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dumbbell Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with a dumbbell in each hand, palms facing forward.\n2. Curl the dumbbells up toward your shoulders.\n3. Keep your upper arms stationary.\n4. Lower the dumbbells with control.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Hammer Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with dumbbells at your sides, palms facing each other.\n2. Curl the dumbbells up while keeping palms facing inward.\n3. Squeeze your biceps at the top.\n4. Lower with control.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Preacher Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "barbell",
      instructions:
        "1. Sit at a preacher bench and rest your upper arms on the pad.\n2. Grip the barbell with an underhand grip.\n3. Curl the bar up toward your shoulders.\n4. Lower the bar until your arms are almost fully extended.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Concentration Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "dumbbell",
      instructions:
        "1. Sit on a bench with legs spread and a dumbbell in one hand.\n2. Rest your elbow against your inner thigh.\n3. Curl the dumbbell up toward your shoulder.\n4. Squeeze at the top and lower with control.\n5. Repeat for the desired number of reps on each arm.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Cable Curl",
      category: "biceps",
      primary_muscles: ["biceps"],
      secondary_muscles: ["forearms"],
      equipment: "cable",
      instructions:
        "1. Stand facing a low cable pulley with a straight bar attachment.\n2. Grip the bar with an underhand grip.\n3. Curl the bar toward your shoulders.\n4. Lower with control, maintaining tension.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },

    // ── Triceps (6) ────────────────────────────────────────
    {
      id: id(),
      name: "Tricep Pushdown",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: [],
      equipment: "cable",
      instructions:
        "1. Stand facing a high cable pulley with a straight bar or rope.\n2. Grip the attachment with an overhand grip.\n3. Push the bar down until your arms are fully extended.\n4. Slowly return to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Skull Crushers",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: [],
      equipment: "barbell",
      instructions:
        "1. Lie on a flat bench holding a barbell with arms extended above your chest.\n2. Bend your elbows to lower the bar toward your forehead.\n3. Keep your upper arms stationary.\n4. Extend your arms to press the bar back up.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Overhead Tricep Extension",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: [],
      equipment: "dumbbell",
      instructions:
        "1. Stand or sit holding a dumbbell overhead with both hands.\n2. Lower the dumbbell behind your head by bending your elbows.\n3. Keep your upper arms close to your ears.\n4. Extend your arms to raise the dumbbell back overhead.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dips (Triceps)",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: ["chest", "shoulders"],
      equipment: "bodyweight",
      instructions:
        "1. Mount the dip bars and keep your torso upright.\n2. Lower your body by bending your elbows to about 90 degrees.\n3. Press back up to the starting position.\n4. Keep your body vertical to emphasize triceps.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Close-Grip Bench Press",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: ["chest", "shoulders"],
      equipment: "barbell",
      instructions:
        "1. Lie on a flat bench and grip the barbell with hands shoulder-width apart.\n2. Unrack the bar and lower it to your lower chest.\n3. Keep your elbows close to your body.\n4. Press the bar back up until arms are extended.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Tricep Kickbacks",
      category: "triceps",
      primary_muscles: ["triceps"],
      secondary_muscles: [],
      equipment: "dumbbell",
      instructions:
        "1. Bend forward at the hips with a dumbbell in one hand.\n2. Keep your upper arm parallel to your torso.\n3. Extend your forearm back until your arm is straight.\n4. Squeeze your tricep at the top.\n5. Lower and repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },

    // ── Legs (12) ──────────────────────────────────────────
    {
      id: id(),
      name: "Squat (Barbell)",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["hamstrings", "core"],
      equipment: "barbell",
      instructions:
        "1. Place the barbell on your upper back and unrack it.\n2. Stand with feet shoulder-width apart.\n3. Bend your knees and hips to lower your body.\n4. Descend until your thighs are parallel to the floor.\n5. Drive through your heels to stand back up.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Leg Press",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["hamstrings"],
      equipment: "machine",
      instructions:
        "1. Sit in the leg press machine with feet shoulder-width on the platform.\n2. Release the safety handles.\n3. Lower the platform by bending your knees to about 90 degrees.\n4. Press the platform back up without locking your knees.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Romanian Deadlift",
      category: "legs",
      primary_muscles: ["hamstrings", "glutes"],
      secondary_muscles: ["back", "core"],
      equipment: "barbell",
      instructions:
        "1. Stand holding a barbell at hip level.\n2. Push your hips back and lower the bar along your legs.\n3. Keep your back flat and knees slightly bent.\n4. Lower until you feel a stretch in your hamstrings.\n5. Drive your hips forward to return to standing.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Lunges",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["hamstrings", "core"],
      equipment: "bodyweight",
      instructions:
        "1. Stand with feet hip-width apart.\n2. Step forward with one leg and lower your body.\n3. Both knees should bend to about 90 degrees.\n4. Push through your front heel to return to standing.\n5. Alternate legs and repeat.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Leg Extension",
      category: "legs",
      primary_muscles: ["quads"],
      secondary_muscles: [],
      equipment: "machine",
      instructions:
        "1. Sit in the leg extension machine and adjust the pad.\n2. Extend your legs until they are straight.\n3. Hold briefly at the top.\n4. Lower the weight back down with control.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Leg Curl",
      category: "legs",
      primary_muscles: ["hamstrings"],
      secondary_muscles: ["calves"],
      equipment: "machine",
      instructions:
        "1. Lie face down on the leg curl machine.\n2. Adjust the pad so it rests on your lower calves.\n3. Curl your legs up toward your glutes.\n4. Squeeze your hamstrings at the top.\n5. Lower with control and repeat.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Calf Raise",
      category: "legs",
      primary_muscles: ["calves"],
      secondary_muscles: [],
      equipment: "machine",
      instructions:
        "1. Stand on a calf raise machine or step with the balls of your feet.\n2. Rise up on your toes as high as possible.\n3. Hold briefly at the top.\n4. Lower your heels below the platform for a stretch.\n5. Repeat for the desired number of reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Bulgarian Split Squat",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["hamstrings", "core"],
      equipment: "dumbbell",
      instructions:
        "1. Stand with one foot on a bench behind you.\n2. Hold dumbbells at your sides.\n3. Lower your body by bending your front knee.\n4. Descend until your front thigh is parallel to the floor.\n5. Push through your front heel to return to standing.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Hip Thrust",
      category: "legs",
      primary_muscles: ["glutes"],
      secondary_muscles: ["hamstrings", "core"],
      equipment: "barbell",
      instructions:
        "1. Sit on the floor with your upper back against a bench.\n2. Roll a barbell over your hips.\n3. Drive through your heels to lift your hips.\n4. Squeeze your glutes at the top.\n5. Lower your hips and repeat.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Goblet Squat",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["core"],
      equipment: "kettlebell",
      instructions:
        "1. Hold a kettlebell at your chest with both hands.\n2. Stand with feet slightly wider than shoulder-width.\n3. Squat down, keeping your elbows inside your knees.\n4. Descend until your thighs are parallel to the floor.\n5. Drive through your heels to stand back up.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Step-ups",
      category: "legs",
      primary_muscles: ["quads", "glutes"],
      secondary_muscles: ["hamstrings"],
      equipment: "bodyweight",
      instructions:
        "1. Stand facing a bench or elevated platform.\n2. Step up with one foot, pressing through your heel.\n3. Bring your other foot up to stand on the platform.\n4. Step back down with the trailing leg.\n5. Alternate legs and repeat.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Hack Squat",
      category: "legs",
      primary_muscles: ["quads"],
      secondary_muscles: ["glutes", "hamstrings"],
      equipment: "machine",
      instructions:
        "1. Position yourself in the hack squat machine with shoulders under the pads.\n2. Place feet shoulder-width apart on the platform.\n3. Release the safety handles.\n4. Lower your body by bending your knees to about 90 degrees.\n5. Press back up without locking your knees.",
      difficulty: "intermediate",
      is_custom: false,
    },

    // ── Core (8) ───────────────────────────────────────────
    {
      id: id(),
      name: "Plank",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: ["shoulders"],
      equipment: "bodyweight",
      instructions:
        "1. Get into a push-up position on your forearms.\n2. Keep your body in a straight line from head to heels.\n3. Engage your core and hold the position.\n4. Avoid letting your hips sag or pike up.\n5. Hold for the desired duration.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Crunches",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: [],
      equipment: "bodyweight",
      instructions:
        "1. Lie on your back with knees bent and feet flat.\n2. Place your hands behind your head.\n3. Curl your upper body toward your knees.\n4. Squeeze your abs at the top.\n5. Lower back down and repeat.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Russian Twist",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: [],
      equipment: "bodyweight",
      instructions:
        "1. Sit on the floor with knees bent and feet slightly elevated.\n2. Lean back slightly and clasp your hands together.\n3. Rotate your torso to the right, touching the floor.\n4. Rotate to the left, touching the floor.\n5. Continue alternating for the desired reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Hanging Leg Raise",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: ["forearms"],
      equipment: "bodyweight",
      instructions:
        "1. Hang from a pull-up bar with arms fully extended.\n2. Raise your legs until they are parallel to the floor.\n3. Keep your legs straight throughout.\n4. Lower your legs with control.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Ab Wheel Rollout",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: ["shoulders", "lats"],
      equipment: "other",
      instructions:
        "1. Kneel on the floor holding an ab wheel.\n2. Roll the wheel forward, extending your body.\n3. Keep your core tight and back flat.\n4. Roll back to the starting position.\n5. Repeat for the desired number of reps.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Dead Bug",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: [],
      equipment: "bodyweight",
      instructions:
        "1. Lie on your back with arms extended toward the ceiling.\n2. Lift your legs with knees bent at 90 degrees.\n3. Extend your right arm and left leg simultaneously.\n4. Return to the starting position.\n5. Repeat on the opposite side and alternate.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Mountain Climbers",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: ["shoulders", "quads"],
      equipment: "bodyweight",
      instructions:
        "1. Start in a push-up position.\n2. Drive one knee toward your chest.\n3. Quickly switch legs, extending the first leg back.\n4. Continue alternating at a brisk pace.\n5. Repeat for the desired duration or reps.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Cable Woodchop",
      category: "core",
      primary_muscles: ["core"],
      secondary_muscles: ["shoulders"],
      equipment: "cable",
      instructions:
        "1. Set a cable pulley to a high position.\n2. Stand sideways to the machine and grip the handle.\n3. Pull the handle diagonally down and across your body.\n4. Rotate your torso while keeping your arms extended.\n5. Return with control and repeat, then switch sides.",
      difficulty: "intermediate",
      is_custom: false,
    },

    // ── Cardio (6) ─────────────────────────────────────────
    {
      id: id(),
      name: "Running",
      category: "cardio",
      primary_muscles: ["quads", "hamstrings", "calves"],
      secondary_muscles: ["core", "glutes"],
      equipment: "bodyweight",
      instructions:
        "1. Start with a light jog to warm up.\n2. Maintain an upright posture with arms swinging naturally.\n3. Land on the midfoot and push off through your toes.\n4. Keep a steady breathing pattern.\n5. Cool down with a slower pace at the end.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Cycling",
      category: "cardio",
      primary_muscles: ["quads", "hamstrings"],
      secondary_muscles: ["calves", "glutes"],
      equipment: "machine",
      instructions:
        "1. Adjust the seat height so your leg is slightly bent at the bottom.\n2. Start pedaling at a moderate pace.\n3. Maintain a smooth, circular pedaling motion.\n4. Adjust resistance for desired intensity.\n5. Cool down with a few minutes of easy pedaling.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Rowing",
      category: "cardio",
      primary_muscles: ["back", "quads"],
      secondary_muscles: ["biceps", "core", "hamstrings"],
      equipment: "machine",
      instructions:
        "1. Sit on the rowing machine and strap your feet in.\n2. Grab the handle with an overhand grip.\n3. Drive with your legs first, then lean back and pull the handle to your chest.\n4. Extend your arms, lean forward, and bend your knees to return.\n5. Repeat in a smooth, continuous motion.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Jump Rope",
      category: "cardio",
      primary_muscles: ["calves"],
      secondary_muscles: ["quads", "shoulders", "core"],
      equipment: "other",
      instructions:
        "1. Hold the jump rope handles at your sides.\n2. Swing the rope overhead and jump as it passes under your feet.\n3. Keep your jumps small and land on the balls of your feet.\n4. Use your wrists to turn the rope, not your arms.\n5. Continue for the desired duration.",
      difficulty: "beginner",
      is_custom: false,
    },
    {
      id: id(),
      name: "Burpees",
      category: "cardio",
      primary_muscles: ["full_body"],
      secondary_muscles: ["chest", "quads", "core"],
      equipment: "bodyweight",
      instructions:
        "1. Stand with feet shoulder-width apart.\n2. Drop into a squat and place your hands on the floor.\n3. Kick your feet back into a push-up position.\n4. Perform a push-up, then jump your feet back to your hands.\n5. Jump up explosively with arms overhead.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Swimming",
      category: "cardio",
      primary_muscles: ["back", "shoulders"],
      secondary_muscles: ["core", "lats", "quads"],
      equipment: "other",
      instructions:
        "1. Choose a stroke (freestyle, backstroke, breaststroke).\n2. Maintain a streamlined body position in the water.\n3. Coordinate your arm pulls with your leg kicks.\n4. Breathe rhythmically to one side or during recovery.\n5. Swim for the desired distance or time.",
      difficulty: "beginner",
      is_custom: false,
    },

    // ── Full Body (6) ──────────────────────────────────────
    {
      id: id(),
      name: "Clean and Press",
      category: "full_body",
      primary_muscles: ["full_body"],
      secondary_muscles: ["shoulders", "quads", "back", "core"],
      equipment: "barbell",
      instructions:
        "1. Stand over a barbell with feet shoulder-width apart.\n2. Deadlift the bar to hip level.\n3. Explosively pull the bar to your shoulders (the clean).\n4. Press the bar overhead until arms are locked out.\n5. Lower the bar back to your shoulders, then to the floor.",
      difficulty: "advanced",
      is_custom: false,
    },
    {
      id: id(),
      name: "Thrusters",
      category: "full_body",
      primary_muscles: ["quads", "shoulders"],
      secondary_muscles: ["glutes", "core", "triceps"],
      equipment: "barbell",
      instructions:
        "1. Hold a barbell at shoulder height in a front rack position.\n2. Squat down until thighs are parallel to the floor.\n3. Drive up explosively and press the bar overhead.\n4. Lower the bar back to shoulder height.\n5. Immediately descend into the next squat.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Turkish Get-up",
      category: "full_body",
      primary_muscles: ["full_body"],
      secondary_muscles: ["core", "shoulders", "glutes"],
      equipment: "kettlebell",
      instructions:
        "1. Lie on your back holding a kettlebell above your shoulder.\n2. Roll onto your elbow, then your hand.\n3. Lift your hips and sweep your leg under your body to kneel.\n4. Stand up while keeping the kettlebell overhead.\n5. Reverse the steps to return to the floor.",
      difficulty: "advanced",
      is_custom: false,
    },
    {
      id: id(),
      name: "Kettlebell Swing",
      category: "full_body",
      primary_muscles: ["glutes", "hamstrings"],
      secondary_muscles: ["core", "shoulders", "back"],
      equipment: "kettlebell",
      instructions:
        "1. Stand with feet wider than shoulder-width, kettlebell on the floor.\n2. Hinge at your hips and grip the kettlebell with both hands.\n3. Swing the kettlebell between your legs.\n4. Drive your hips forward to swing the kettlebell to chest height.\n5. Control the swing back down and repeat.",
      difficulty: "intermediate",
      is_custom: false,
    },
    {
      id: id(),
      name: "Man Makers",
      category: "full_body",
      primary_muscles: ["full_body"],
      secondary_muscles: ["chest", "back", "shoulders", "core"],
      equipment: "dumbbell",
      instructions:
        "1. Start in a push-up position holding dumbbells.\n2. Perform a push-up.\n3. Row one dumbbell to your hip, then the other.\n4. Jump your feet toward your hands.\n5. Clean the dumbbells and press them overhead.",
      difficulty: "advanced",
      is_custom: false,
    },
    {
      id: id(),
      name: "Bear Crawl",
      category: "full_body",
      primary_muscles: ["core", "shoulders"],
      secondary_muscles: ["quads", "triceps"],
      equipment: "bodyweight",
      instructions:
        "1. Start on all fours with knees hovering just above the ground.\n2. Move your right hand and left foot forward simultaneously.\n3. Then move your left hand and right foot forward.\n4. Keep your hips low and back flat.\n5. Continue crawling for the desired distance.",
      difficulty: "beginner",
      is_custom: false,
    },
  ];
}
