/**
 * Public type surface for the CableSnap Wear OS bridge.
 *
 * **M0 status:** all types are exported but no implementation backs them yet.
 * The watch APK is empty and `:wear` does not transmit any messages. M1 will
 * land the DataLayer wrapper; M2..M4 fill in the watch UI screens; M5 wires
 * the disconnect-tolerant durable queue.
 *
 * See `.plans/PLAN-BLD-716.md` §"Communication protocol" for the full wire
 * contract these types target. The shapes here are deliberately conservative —
 * payload schema may tighten before M3 once we lock the `MessageClient` paths.
 */

/**
 * Payload broadcast from the watch when the user taps "Complete Set".
 *
 * `completedAt` is generated by the watch's monotonic clock (per plan
 * §"Clock authority"). The phone clamps the value to
 * `[sessionStart, now() + 60s]` on reconcile.
 */
export interface WatchSetCompletePayload {
  sessionId: string;
  exerciseId: string;
  setNumber: number;
  weight: number;
  reps: number;
  /** Watch monotonic clock, milliseconds since epoch. */
  completedAt: number;
}

/**
 * Workout-control event broadcast from the watch.
 *
 * The phone is the source of truth — these events are advisory; the phone
 * reconciles its own state and broadcasts the new state back via DataClient.
 */
export type WatchWorkoutControl = "pause" | "resume" | "finish" | "cancel";

export interface WatchWorkoutControlPayload {
  sessionId: string;
  control: WatchWorkoutControl;
  /** Watch monotonic clock, milliseconds since epoch. */
  triggeredAt: number;
}

/**
 * Mutation events: add / delete / update of an existing set on the watch.
 * `weight` and `reps` are present for `update` and `add`; absent for `delete`.
 */
export type WatchSetMutation = "add" | "delete" | "update";

export interface WatchSetMutatePayload {
  sessionId: string;
  exerciseId: string;
  setNumber: number;
  mutation: WatchSetMutation;
  weight?: number;
  reps?: number;
  /** Watch monotonic clock, milliseconds since epoch. */
  mutatedAt: number;
}

/**
 * Subscription handle returned by every `onXxx` listener registration.
 * Calling `.remove()` is idempotent.
 */
export interface WatchSubscription {
  remove(): void;
}

/**
 * Listener signatures. All listeners are called on the JS thread by the
 * phone-side bridge; native callbacks are translated through
 * `DeviceEventEmitter` per plan §"Phone-side bridge concurrency model".
 */
export type WatchSetCompleteListener = (
  payload: WatchSetCompletePayload,
) => void;
export type WatchSetMutateListener = (payload: WatchSetMutatePayload) => void;
export type WatchWorkoutControlListener = (
  payload: WatchWorkoutControlPayload,
) => void;
