repo_url: https://alankyshum.github.io/cablesnap/repo
repo_name: CableSnap F-Droid Repo
repo_description: Workout tracker optimized for cable machines — supports all major exercises
archive_older: 3

keystore: keystore.p12
keystorepass: {env: FDROID_KEY_STORE_PASS}
keypass: {env: FDROID_KEY_STORE_PASS}
repo_keyalias: fdroid-repo
keydname: CN=CableSnap F-Droid Repo, O=alankyshum
