#!/usr/bin/env bash
# daily-audit.sh — BLD-480 regression-catcher + daily visual audit driver.
#
# Runs the `completed-workout` and `workout-history` scenario specs against:
#   1. current HEAD (the commit under test today)
#   2. BLD_480_PRE_FIX_SHA (`cce2ac1f8…`) — represented by a STATIC GOLDEN
#      FIXTURE PNG checked into `tests/fixtures/regression-catcher/`. We no
#      longer rebuild that old tree on every run; see BLD-959 for rationale
#      (Node 20 / old Expo SDK no longer build on the workspace image).
#
# Each HEAD scenario emits four PNGs per viewport (BLD-744):
#   <scenario>/<viewport>.png                  ← baseline
#   <scenario>/<viewport>-deuteranopia.png     ← CVD: red-green (~6% males)
#   <scenario>/<viewport>-protanopia.png       ← CVD: red-cone (~2% males)
#   <scenario>/<viewport>-tritanopia.png       ← CVD: blue-cone (rare)
# Implemented via Chromium DevTools Protocol's
# `Emulation.setEmulatedVisionDeficiency` in `e2e/scenarios/capture-with-cvd.ts`.
#
# The pre-fix fixture is the PERMANENT DAILY SMOKE (QD#1). If the
# ux-designer vision pipeline silently regresses, the audit loop would
# produce green audits indefinitely. `scripts/regression-smoke.sh` runs the
# audit prompt against the fixture and asserts at least one finding matches
# the canonical regex (QD#2). A miss aborts the audit non-zero — that IS
# the alarm.
#
# Refs: BLD-494, BLD-744, BLD-924, BLD-941, BLD-959, TL#6, QD#1, QD#2

set -euo pipefail

# Pinned via `git rev-parse 6f067cc^` on 2026-04-22 — the commit immediately
# BEFORE PR #292 ("fix: remove maxHeight crop on workout summary muscle
# heatmap") merged. Captured into the fixture below by
# .github/workflows/regression-fixture-capture.yml. Do NOT change this
# constant unless the BLD-480 fix is reverted or the parent SHA is re-pinned
# (which also requires re-running the capture workflow).
BLD_480_PRE_FIX_SHA="cce2ac1f828538bf884f91c5e209ab9f6a40d87f"

# Static golden fixture committed at this path. (Re)generated by the manual
# `regression-fixture-capture.yml` workflow on a Node-20 runner.
BLD_480_FIXTURE_PATH="tests/fixtures/regression-catcher/bld-480-pre-fix.png"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

build_static_bundle() {
  # Mirror the CI pattern (.github/workflows/ux-audit.yml): export the web
  # bundle in dev mode so `__DEV__` is true and the `__TEST_SCENARIO__` seed
  # hook in `lib/db/test-seed.ts` actually executes. `--no-minify` keeps the
  # bundle readable for debugging. Static export + `E2E_USE_STATIC=1` causes
  # `playwright.config.ts:webServer` to serve via `npx serve` with COOP/COEP
  # headers (BLD-658), which gives the page `crossOriginIsolated === true`
  # and unlocks SharedArrayBuffer for the expo-sqlite Web Worker. Without
  # this, `useAppInit` short-circuits via `webNeedsUnsupportedFallback`, the
  # DB never inits, the seed never runs, `data-test-ready` never flips, and
  # screenshots come out blank (the original BLD-902 symptom).
  echo "[daily-audit] building static web bundle (--dev for __DEV__ seed hook)…"
  npx --yes expo export -p web --dev --no-minify
  if [[ ! -f dist/index.html ]]; then
    echo "[daily-audit] ERROR: static export produced no dist/index.html — aborting." >&2
    exit 1
  fi
}

run_scenarios() {
  local label="$1"
  local commit_sha="$2"
  echo ""
  echo "=========================================================="
  echo "[daily-audit] running scenarios against $label ($commit_sha)"
  echo "=========================================================="
  E2E_USE_STATIC=1 COMMIT_SHA="$commit_sha" \
    npx playwright test e2e/scenarios/ --project=mobile
}

ORIGINAL_REF="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$ORIGINAL_REF" == "HEAD" ]]; then
  ORIGINAL_REF="$(git rev-parse HEAD)"
fi

cleanup() {
  echo "[daily-audit] restoring $ORIGINAL_REF"
  # Discard any dirty state from the HEAD scenario run before returning.
  # `-e .pixelslop` (BLD-943 #1 / BLD-959): preserve the audit output dir
  # even though it is gitignored. `git clean -fd` without the exclusion
  # nukes `.pixelslop/` because gitignored dirs are still removed by `-fd`
  # unless explicitly excluded — losing today's audit bundle on a partial
  # scenario failure.
  git reset --hard --quiet || true
  git clean -fdq -e .pixelslop || true
  git checkout --quiet "$ORIGINAL_REF" || true
}
trap cleanup EXIT

# 1) Today's HEAD
# BLD-966: capture HEAD scenario exit code without aborting — the smoke
# check (step 3) is the vision-pipeline trust anchor and MUST run even if
# HEAD scenarios fail. We re-export the failure at the end so HEAD failures
# still abort the audit non-zero (preserving existing behavior). Rationale:
# a flaky HEAD spec must NOT silence the smoke alarm — that's precisely
# when the alarm matters most.
HEAD_SHA="$(git rev-parse HEAD)"
build_static_bundle
set +e
run_scenarios "HEAD" "$HEAD_SHA"
HEAD_RC=$?
set -e

# Move HEAD captures into a date-stamped subdir so subsequent steps don't
# clobber them. Tolerate a missing/empty HEAD_OUT when scenarios failed
# before producing any captures — we still want to run the smoke check.
HEAD_OUT=".pixelslop/screenshots/scenarios"
AUDIT_DATE_DIR=".pixelslop/audits/$(date -u +%Y-%m-%d)"
HEAD_COPY="$AUDIT_DATE_DIR/HEAD"
mkdir -p "$HEAD_COPY"
if [[ -d "$HEAD_OUT" ]] && compgen -G "$HEAD_OUT/*" > /dev/null; then
  cp -r "$HEAD_OUT"/* "$HEAD_COPY"/
else
  echo "[daily-audit] note: no HEAD captures to copy (HEAD scenarios may have failed)" >&2
fi

# 2) BLD-480 pre-fix regression-catcher — static fixture (BLD-959).
# We copy the pinned PNG into the same directory layout the ux-designer
# agent expects (`<scenario>/<viewport>.png`), so downstream tooling
# (audit-bundle.sh, ux-designer review) treats it identically to a freshly
# captured screenshot.
PINNED_OUT="$AUDIT_DATE_DIR/BLD_480_PRE_FIX"
PINNED_SCENARIO_DIR="$PINNED_OUT/completed-workout"
mkdir -p "$PINNED_SCENARIO_DIR"

if [[ ! -f "$BLD_480_FIXTURE_PATH" ]]; then
  echo "[daily-audit] ERROR: missing static fixture at $BLD_480_FIXTURE_PATH" >&2
  echo "[daily-audit] Run .github/workflows/regression-fixture-capture.yml" >&2
  echo "[daily-audit] (workflow_dispatch) to generate it. See BLD-959." >&2
  exit 1
fi

cp "$BLD_480_FIXTURE_PATH" "$PINNED_SCENARIO_DIR/mobile.png"
# Sidecar metadata so the ux-designer agent can distinguish the static
# fixture from live captures and see provenance at a glance.
cat > "$PINNED_SCENARIO_DIR/mobile.json" <<EOF
{
  "scenario": "completed-workout",
  "label": "post-workout-summary",
  "viewport": "mobile",
  "commitSha": "$BLD_480_PRE_FIX_SHA",
  "source": "static-fixture",
  "fixturePath": "$BLD_480_FIXTURE_PATH",
  "capturedAt": null,
  "note": "Pinned BLD-480 pre-fix screenshot. Captured once via .github/workflows/regression-fixture-capture.yml; see fixture README for provenance."
}
EOF

echo "[daily-audit] copied static fixture → $PINNED_SCENARIO_DIR/mobile.png"

# 3) Vision-pipeline trust-anchor smoke (QD#2 / BLD-959).
# We assert that running the audit prompt against the pre-fix fixture
# still produces a finding matching the canonical regex. Failure here =
# vision pipeline silent degradation = ABORT the audit (HEAD findings
# cannot be trusted today).
#
# BLD-966: smoke RC dominates. Run unconditionally even if HEAD scenarios
# failed. If smoke fails → abort with smoke RC (trust anchor takes
# priority). If smoke passes but HEAD failed → abort with HEAD RC, log
# that the pipeline itself is healthy (HEAD failure is a real regression).
SMOKE_FINDINGS="$PINNED_OUT/smoke-findings.txt"
echo ""
echo "[daily-audit] running regression-smoke against fixture …"
set +e
FINDINGS_OUT="$SMOKE_FINDINGS" \
  scripts/regression-smoke.sh "$BLD_480_FIXTURE_PATH"
SMOKE_RC=$?
set -e

if [[ $SMOKE_RC -ne 0 ]]; then
  echo "[daily-audit] 🚨 FATAL: regression-smoke FAILED (vision-pipeline trust anchor)." >&2
  echo "[daily-audit] Today's HEAD findings MUST NOT be trusted." >&2
  exit $SMOKE_RC
fi

if [[ $HEAD_RC -ne 0 ]]; then
  echo "[daily-audit] HEAD scenarios failed (rc=$HEAD_RC) but smoke PASSED — vision pipeline is healthy, the HEAD failure is a real regression." >&2
  echo "[daily-audit] regression-smoke: PASS (findings → $SMOKE_FINDINGS)"
  exit $HEAD_RC
fi

echo ""
echo "[daily-audit] bundles ready at $HEAD_COPY and $PINNED_OUT"
echo "[daily-audit] regression-smoke: PASS (findings → $SMOKE_FINDINGS)"
echo "[daily-audit] next step: scripts/audit-bundle.sh uploads to GH Releases,"
echo "[daily-audit] then ux-designer agent pulls + reviews."
